config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/users/:user_id/trophy' => 'users#trophy', as: :trophy

  resources :users, only: [:new, :create, :show] do
    resources :contracts
    resources :agents
    resources :clubs
    resources :players
  end

end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :players
  has_many :agents, through: :players
  has_many :contracts
  belongs_to :user

  validates :name, presence: true
  validates :city, presence: true
  validates :nation, presence: true
  validates :league_division, presence: true
  validates_uniqueness_of :name, :scope => :user_id
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authorization, except: [:create, :update]

  def index
    @clubs = Club.where(user_id: session[:user_id])
  end

  def show
    if session[:user_id] != Club.find_by_id(params[:id]).user.id
      redirect_to user_path(User.find_by_id(session[:user_id]), error_message: "that is not your data")
    end
    @club = Club.find_by_id(params[:id])
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      redirect_to user_club_path(@club.user, @club)
    else
      render 'clubs/new'
    end
  end

  def edit
    if session[:user_id] != Club.find_by_id(params[:id]).user.id
      redirect_to user_path(User.find_by_id(session[:user_id]), error_message: "that is not your data")
    end
    @club = Club.find_by_id(params[:id])
  end

  def update
    @club = Club.find_by(user_id: params[:club][:user_id], id: params[:club][:id])
    if @club.update(club_params)
      redirect_to user_club_path(@club.user, @club)
    else
      render 'clubs/edit'
    end
  end

  def destroy
    @club = Club.find_by(user_id: params[:user_id], id: params[:id])
    @club.delete
    redirect_to user_clubs_path(User.find_by_id(session[:user_id]))
  end

  def club_params
    params.require(:club).permit(:name, :city, :nation, :league_division, :user_id, :id)
  end

end

app/views/clubs/_error.html.erb
<% if @club.errors %>
<% @club.errors.full_messages.each do |e| %>
<p><%= e %></p><br>
<% end %>
<% end %>

app/views/clubs/edit.html.erb
<h2>Edit Club</h2><br>

<%= render 'error' %>

<%= form_tag ({controller: "clubs", action: "update", method: "patch"}) do %>
<input type="hidden" name="_method" value="patch" />
<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

<label>Name:</label>
<%= text_field_tag "club[name]", @club.name %><br>

<label>Resident City:</label>
<%= text_field_tag "club[city]", @club.city %><br>

<label>Resident Nation:</label>
<%= text_field_tag "club[nation]", @club.nation %><br>

<label>League/Division:</label>
<%= text_field_tag "club[league_division]", @club.league_division %><br>

<%= hidden_field_tag "club[user_id]", @club.user_id %><br>

<%= hidden_field_tag "club[id]", @club.id %><br>

<%= submit_tag "Update Club" %>
<% end %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/clubs/index.html.erb
<h1>Your Clubs</h1>

<% if !@clubs.nil? %>
<% @clubs.each do |club| %>
<% if club.valid? %>
<%= link_to "#{club.name}", user_club_path(club.user, club) %><br>
<% end %>
<% end %>
<% end %>
<br>
<%= link_to "Create a New Club", new_user_club_path(User.find_by_id(session[:user_id])) %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/clubs/new.html.erb
<h2>Create a New Club</h2><br>

<%= render 'error' %>

<%= form_tag ({controller: "clubs", action: "create", method: "post"}) do %>

<label>Name:</label>
<%= text_field_tag "club[name]" %><br>

<label>Resident City:</label>
<%= text_field_tag "club[city]" %><br>

<label>Resident Nation:</label>
<%= text_field_tag "club[nation]" %><br>

<label>League/Division:</label>
<%= text_field_tag "club[league_division]" %><br>

<%= hidden_field_tag "club[user_id]", session[:user_id] %><br>

<%= submit_tag "Create Club" %>
<% end %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/clubs/show.html.erb
<h1><%= @club.name %></h1>
<p>Resident City: <%= @club.city %></p><br>
<p>Resident Nation: <%= @club.nation %></p><br>
<p>League/Division: <%= @club.league_division %></p>

<%= link_to "Edit: #{@club.name}", edit_user_club_path(@club.user, @club) %>

<%= form_tag ({controller: "clubs", action: "destroy", method: "delete"}) do %>
<input type="hidden" name="_method" value="delete" />
<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
<%= submit_tag "Delete Club" %>
<% end %>

<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>