config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/users/:user_id/trophy' => 'users#trophy', as: :trophy

  resources :users, only: [:new, :create, :show] do
    resources :contracts
    resources :agents
    resources :clubs
    resources :players
  end

end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :player
  belongs_to :club
  belongs_to :agent
  belongs_to :user

  validates :status, presence: true
  validate :status_terminology
  validate :contract_status_accurate?

  scope :in_effect, -> { where(status: "in effect") }
  # scope :highest_contracts_salary

  def status_terminology
    if self.status != "in the works" && self.status != "pending" && self.status != "in effect" && self.status != "completed" && self.status != "terminated early" && self.status != "dead"
      errors.add(:contract, "Each contract status must adhere to status terminology")
    end
  end

  def contract_status_accurate?
    if Contract.in_effect.find_by(player: self.player) != self && self.status == "in effect"
      errors.add(:contract, "This contract would cause its player's contract statuses to be inaccurate. Each player must have at most one contract that is in effect at a time")
    end
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :authorization, except: [:create, :update]

  def index
    @contracts = Contract.where(user_id: session[:user_id])
  end

  def show
    if session[:user_id] != Contract.find_by_id(params[:id]).user.id
      redirect_to user_path(User.find_by_id(session[:user_id]), error_message: "that is not your data")
    end
    @contract = Contract.find_by_id(params[:id])
  end

  def new
    @contract = Contract.new
  end

  def create
    @contract = Contract.new(contract_params)
    if @contract.save
      redirect_to user_contract_path(@contract.user, @contract)
    else
      render 'contracts/new'
    end
  end

  def edit
    if session[:user_id] != Contract.find_by_id(params[:id]).user.id
      redirect_to user_path(User.find_by_id(session[:user_id]), error_message: "that is not your data")
    end
    @contract = Contract.find_by_id(params[:id])
    @user_id = session[:user_id]
  end

  def update
    @contract = Contract.find_by(user_id: params[:contract][:user_id], id: params[:contract][:id])
    if @contract.update(contract_params)
      redirect_to user_contract_path(@contract.user, @contract)
    else
      render 'contracts/edit'
    end
  end

  def destroy
    @contract = Contract.find_by(user_id: params[:user_id], id: params[:id])
    @contract.delete
    redirect_to user_contracts_path(User.find_by_id(session[:user_id]))
  end

  def contract_params
    params.require(:contract).permit(:length, :weekly_salary, :transfer_fee, :unusual_clauses, :status, :player_id, :club_id, :agent_id, :user_id)
  end

end

app/views/contracts/_error.html.erb
<% if @contract.errors %>
<% @contract.errors.full_messages.each do |e| %>
<text><%= e %></text><br>
<% end %>
<% end %>

app/views/contracts/edit.html.erb
<% if @contract.valid? %>
<h2>Edit Contract Between <%= @contract.player.name %> & <%= @contract.club.name %></h2><br>
<%= render 'error' %>
<% else %>
<%= render 'error' %>
<p>Data is needed below to make this contract valid</p>
<label>Player:</label>
<%= collection_select :contract, :player_id, Player.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>

<label>Club:</label>
<%= collection_select :contract, :club_id, Club.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>
<% end %>

<%= form_tag ({controller: "contracts", action: "update", method: "patch"}) do %>
<input type="hidden" name="_method" value="patch" />
<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

<label>Length:</label>
<%= text_field_tag "contract[length]", @contract.length %><br>

<label>Weekly Salary:</label>
<%= text_field_tag "contract[weekly_salary]", @contract.weekly_salary %><br>

<label>Transfer Fee:</label>
<%= text_field_tag "contract[transfer_fee]", @contract.transfer_fee %><br>

<label>Unusual Clauses:</label>
<%= text_field_tag "contract[unusual_clauses]", @contract.unusual_clauses %><br>

<label>Status:</label>
<%= collection_select :contract, :status, Status.all, :wording, :wording %><br>

<%= hidden_field_tag "contract[player_id]", @contract.player_id %>

<%= hidden_field_tag "contract[club_id]", @contract.club_id %>

<label>Agent:</label>
<%= collection_select :contract, :agent_id, Agent.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>

<%= hidden_field_tag "contract[user_id]", @contract.user_id %><br>

<%= hidden_field_tag "contract[id]", @contract.id %><br>

<%= submit_tag "Update Contract" %>
<% end %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/contracts/index.html.erb
<h1>Your Contract Investigations</h1>

<% if !@contracts.nil? %>
<% @contracts.each do |contract| %>
<% if contract.valid? %>
<%= link_to "#{contract.player.name} & #{contract.club.name}", user_contract_path(contract.user, contract) %><br>
<% else %>
<%= link_to "Your data for this contract is currently invalid", user_contract_path(contract.user, contract) %><br>
<% end %>
<% end %>
<% end %>
<br><br>
<%= link_to "Create a New Contract", new_user_contract_path(User.find_by_id(session[:user_id])) %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/contracts/new.html.erb
<h2>Create a New Contract</h2><br>

<%= render 'error' %>

<%= form_tag ({controller: "contracts", action: "create", method: "post"}) do %>

<label>Length:</label>
<%= text_field_tag "contract[length]" %><br>

<label>Weekly Salary:</label>
<%= text_field_tag "contract[weekly_salary]" %><br>

<label>Transfer Fee:</label>
<%= text_field_tag "contract[transfer_fee]" %><br>

<label>Unusual Clauses:</label>
<%= text_field_tag "contract[unusual_clauses]" %><br>

<label>Status:</label>
<%= collection_select :contract, :status, Status.all, :wording, :wording %><br>

<label>Player:</label>
<%= collection_select :contract, :player_id, Player.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>

<label>Club:</label>
<%= collection_select :contract, :club_id, Club.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>

<label>Agent:</label>
<%= collection_select :contract, :agent_id, Agent.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>

<%= hidden_field_tag "contract[user_id]", session[:user_id] %><br>

<%= submit_tag "Create Contract" %>
<% end %>

<p>The agent, club and player you'd like to select must be created prior to selecting them on this form.</p><br>
<%= link_to "Create New Agent", new_user_agent_path(User.find_by_id(session[:user_id])) %><br>
<%= link_to "Create New Club", new_user_club_path(User.find_by_id(session[:user_id])) %><br>
<%= link_to "Create New Player", new_user_player_path(User.find_by_id(session[:user_id])) %><br><br>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/contracts/show.html.erb
<% if @contract.valid? %>
<h1>Contract between <%= @contract.player.name %> and <%= @contract.club.name %></h1>
<p>Contract Length: <%= @contract.length %></p><br>
<p>Weekly Salary: <%= @contract.weekly_salary %></p><br>
<p>Transfer Fee: <%= @contract.transfer_fee %></p><br>
<p>Unusual Clauses: <%= @contract.unusual_clauses %></p><br>
<p>Current Status: <%= @contract.status %></p><br>
<p>Player Agent: <%= @contract.agent.name %></p><br>
<% else %>
<p>Click the link below to add data to this contract</p>
<% end %>

<%= link_to "Edit This Contract", edit_user_contract_path(@contract.user, @contract) %>

<%= form_tag ({controller: "contracts", action: "destroy", method: "delete"}) do %>
<input type="hidden" name="_method" value="delete" />
<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

<%= submit_tag "Delete Contract" %>
<% end %>

<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>