config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/users/:user_id/trophy' => 'users#trophy', as: :trophy

  resources :users, only: [:new, :create, :show] do
    resources :contracts
    resources :agents
    resources :clubs
    resources :players
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :password, presence: true

  def self.session_user_id(user_id)
    User.find_by_id(user_id).id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    already_logged_in
    @user = User.new
  end

  def create
    @user = User.new(name: params[:user][:name], password: params[:user][:password])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'users/new'
    end
  end

  def show
    if_not_logged_in
    not_your_page_id_v
    if_error
    @user = User.find_by_id(params[:id])
  end

  def trophy
    @contracts = Contract.where(user_id: session[:user_id]).order(transfer_fee: :desc)
  end
end

app/views/users/new.html.erb
<% if @error_message %>
<p><%= "#{@error_message}" %></p><br>
<% end %>
<% if @user.errors.full_messages.each do |e| %>
<p><%= e %></p>
<% end %>
<%= form_for(@user) do |f| %>

<%= f.label "Name" %>
<%= f.text_field :name %><br>

<%= f.label "Password" %>
<%= f.text_field :password %><br>

<%= f.submit "Create User" %>
<% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if @error_message %>
<p><%= "#{@error_message}" %></p><br>
<% end %>
<%= link_to "Your Contract Investigations", user_contracts_path(@user) %><br>
<%= link_to "Your Players", user_players_path(@user) %><br>
<%= link_to "Your Clubs", user_clubs_path(@user) %><br>
<%= link_to "Your Agents", user_agents_path(@user), class: 'agents' %><br>

<br><%= link_to "Your Trophies", trophy_path(@user) %><br>
<%= link_to "Logout", logout_path %>

app/views/users/trophy.html.erb
<h1>Highest Value Contracts Investigated</h1>
<% counter = 1 %>
<% @contracts.each do |contract| %>
<% if counter < 4 %>
<%= contract.player.name %><br>
<%= contract.club.name %><br>
<%= contract.transfer_fee %><br><br>
<% counter += 1 %>
<% end %>
<% end %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>