config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/users/:user_id/trophy' => 'users#trophy', as: :trophy

  resources :users, only: [:new, :create, :show] do
    resources :contracts
    resources :agents
    resources :clubs
    resources :players
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :agent
  belongs_to :club
  # belongs_to :contract
  belongs_to :user
  has_many :contracts

  validates :name, presence: true
  validates_uniqueness_of :name, :scope => :user_id
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authorization, except: [:create, :update]

  def index
    @players = Player.where(user_id: session[:user_id])
  end

  def show
    if session[:user_id] != Player.find_by_id(params[:id]).user.id
      redirect_to user_path(User.find_by_id(session[:user_id]), error_message: "that is not your data")
    end
    @player = Player.find_by_id(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
      @player = Player.new(player_params)
      if @player.save
        redirect_to user_player_path(@player.user, @player)
      else
        render 'players/new'
      end
  end

  def edit
    if session[:user_id] != Player.find_by_id(params[:id]).user.id
      redirect_to user_path(User.find_by_id(session[:user_id]), error_message: "that is not your data")
    end
    if_error
    @player = Player.find_by_id(params[:id])
  end

  def update
    @player = Player.find_by(user_id: params[:player][:user_id], id: params[:player][:id])
    if @player.update(player_params)
      redirect_to user_player_path(@player.user, @player)
    else
      render 'players/edit'
    end
  end

  def destroy
    @player = Player.find_by(user_id: params[:user_id], id: params[:id])
    @player.delete
    redirect_to user_players_path(User.find_by_id(session[:user_id]))
  end

  def player_params
    params.require(:player).permit(:name, :country_of_origin, :position, :agent_id, :club_id, :contract_id, :user_id, :id)
  end

end

app/views/players/_error.html.erb
<% if @player.errors %>
<% @player.errors.full_messages.each do |e| %>
<p><%= e %></p><br>
<% end %>
<% end %>

app/views/players/edit.html.erb
<h2>Edit Players</h2><br>

<%= render 'error' %>

<%= form_tag ({controller: "players", action: "update", method: "patch"}) do %>
<input type="hidden" name="_method" value="patch" />
<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>

<label>Name:</label>
<%= text_field_tag "player[name]", @player.name %><br>

<label>Country of Origin:</label>
<%= text_field_tag "player[country_of_origin]", @player.country_of_origin %><br>

<label>Position:</label>
<%= text_field_tag "player[position]", @player.position %><br>

<label>Agent:</label>
<%= collection_select :player, :agent_id, Agent.where(user_id: session[:user_id]), :id, :name %><br>

<label>Club:</label>
<%= collection_select :player, :club_id, Club.where(user_id: session[:user_id]), :id, :name %><br>

<%= hidden_field_tag "player[user_id]", @player.user_id %><br>

<%= hidden_field_tag "player[id]", @player.id %><br>

<%= submit_tag "Update Player" %>
<% end %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/players/index.html.erb
<h1>Your Players</h1>

<% if !@players.nil? %>
<% @players.all.each do |player| %>
<% if player.valid? %>
<%= link_to "#{player.name}", user_player_path(player.user, player) %><br>
<% else %>
<%= link_to "Your data for this player is currently invalid", user_player_path(player.user, player) %><br>
<% end %>
<% end %>
<% end %>
<br>
<%= link_to "Create a New Player", new_user_player_path(User.find_by_id(session[:user_id])) %>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/players/new.html.erb
<h2>Create a New Player</h2><br>

<%= render 'error' %>

<%= form_tag ({controller: "players", action: "create", method: "post"}) do %>

<label>Name:</label>
<%= text_field_tag "player[name]" %><br>

<label>Country of Origin:</label>
<%= text_field_tag "player[country_of_origin]" %><br>

<label>Position:</label>
<%= text_field_tag "player[position]" %><br>

<label>Agent:</label>
<%= collection_select :player, :agent_id, Agent.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>

<label>Club:</label>
<%= collection_select :player, :club_id, Club.where(user_id: session[:user_id]), :id, :name, {:include_blank => 'none'} %><br>

<%= hidden_field_tag "player[user_id]", session[:user_id] %><br>

<%= submit_tag "Create Player" %>
<% end %>

<p>The agent and club you'd like to select must be created prior to selecting them on this form.</p><br>
<%= link_to "Create New Agent", new_user_agent_path(User.find_by_id(session[:user_id])) %><br>
<%= link_to "Create New Club", new_user_club_path(User.find_by_id(session[:user_id])) %><br><br>
<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>

app/views/players/show.html.erb
<% if @player.valid? %>
<h1><%= @player.name %></h1>
<p>Country of Origin: <%= @player.country_of_origin %></p>
<p>Position: <%= @player.position %></p>
<p>Club: <%= @player.club.name %></p>
<p>Agent: <%= @player.agent.name %></p>
<% else %>
<p>Click the link below to add data to this player</p>
<% end %>

<%= link_to "Edit: #{@player.name}", edit_user_player_path(@player.user, @player) %>

<%= form_tag ({controller: "players", action: "destroy", method: "delete"}) do %>
<input type="hidden" name="_method" value="delete" />
<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
<%= submit_tag "Delete Player" %>
<% end %>

<br><label>All Contracts (past, current, future):</label><br><br>
<% if @player.contracts.length > 0 %>
<% counter = 1 %>
<% @player.contracts.each do |contract| %>
<%= link_to "Contract #{counter}: with #{contract.club.name}: #{contract.status}", user_contract_path(contract.user, contract) %><br>
<% counter += 1 %>
<% end %>
<% end %>
<br>

<br><%= link_to "Your Home Page", user_path(User.find_by_id(session[:user_id])) %>